URL: #xstz登录URL
 https://uc.xsmcfx.com/login.html 
USERNAME: # 测试用户名
 !!str 520112620    
PWD:
 xs170999SS
log: #log日志相关参数
    file_name: XSTZ_WAP.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
email:    #发送email参数
    title: 鑫圣投资报告
    message: XSTZ_WAP自动测试报告
    receiver: 991378415@qq.com;failymao@live.com
    HOST: smtp.ym.163.com
    sender: maoyifei@magiccompass.cn
    password: XXXX
URL_BD: #百度测试地址
 http://www.baidu.com
ip:   #socket 接口地址参数
 127.0.0.1 
port:
 8080
# 钉钉播报参数
dd_api:
 https://oapi.dingtalk.com/robot/send?access_token=a91c216ece89737fab0dad1f8621e7cf1de09131cf38c960f26209e7cf624617
# report_html地址
report_url:
  !!str http://192.168.0.9/%s
# influxdb服务器连接参数
conn_dict:
    host: !!str 192.168.0.187
    port: 8086
    username: ''
    password: ''
    database: XSTZ_AutoTest
## 入金，跳转第三方支付页面，输入金额，备注信息
money:
 1
remark:
 Channel 1,test
deposit_URL:
  https://deposit.xsmcfx.com/injection/injection-amount.html

